name: 'Issue Close Worklfows'

on:
  issue_comment:
    types: [ created ]

jobs:
  comment-job:
    name: 'Comment Job'
    if: github.event.issue.comments.body == 'close'
    runs-on: ubuntu-latest

    steps:
    - name: Close Issue
      uses: peter-evans/close-issue@v3